### ISSUE TITLE
Key Error on file contexts

### ISSUE THREAD

**Issue by hkethi002** [flywheel-io/bids-client#6]
When uploading the 7t_trt dataset, I kept running into this error:
```
Traceback (most recent call last):
  File "code/upload_bids.py", line 878, in <module>
    rootdir, args.hierarchy_type
  File "code/upload_bids.py", line 554, in upload_bids_dir
    meta_info = fill_in_properties(context, full_path)
  File "code/upload_bids.py", line 298, in fill_in_properties
    meta_info = context['file']['info']
KeyError: 'info'
```
I'm not sure if the simple fix of using `.get('info')` is the best method incase there is a deeper problem here.

**Comment by hkethi002** [comment]
Closed via #12
